build:
    nodes:
        analysis:
            environment:
                php:
                    version: 7.3
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    - phpcs-run
    dependencies:
        override:
            - composer install --no-interaction --prefer-dist

checks:
    php: true

build_failure_conditions:
    - 'elements.rating(<= C).new.exists'                        # No new classes/methods with a rating of C or worse allowed
    - 'issues.severity(>= MAJOR).new.exists'                    # New issues of major or higher severity
    - 'project.metric_change("scrutinizer.test_coverage", < 0)' # Code Coverage decreased from previous inspection
