build:
    nodes:
        tests: # disables default
            tests:
                override:
                    - true

        analysis:
            environment:
                php:
                    version: 7.3
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    - phpcs-run
        coverage:
            tests:
                override:
                -   command: ./vendor/bin/simple-phpunit --coverage-clover=coverage.xml
                    coverage:
                        file: coverage.xml
                        format: clover
    dependencies:
        override:
            - composer install --no-interaction --prefer-dist
            - composer update --working-dir=.tools/php-cs-fixer

checks:
    php: true

build_failure_conditions:
    - 'elements.rating(<= C).new.exists'                        # No new classes/methods with a rating of C or worse allowed
    - 'issues.severity(>= MAJOR).new.exists'                    # New issues of major or higher severity
    - 'project.metric_change("scrutinizer.test_coverage", < 0)' # Code Coverage decreased from previous inspection
