services:
    _defaults:
        autowire: true
        autoconfigure: true

    FH\Bundle\MailerBundle\Transport\Smtp\SmtpNoTlsTransportFactory:
        tags:
            - { name: 'mailer.transport_factory' }
